const countries = [
  { name: "Portugal", flag: "🇵🇹", code: "PT", dialCode: "+351" },
  { name: "Afeganistão", flag: "🇦🇫", code: "AF", dialCode: "+93" },
  { name: "Ilhas Åland", flag: "🇦🇽", code: "AX", dialCode: "+358" },
  { name: "Albânia", flag: "🇦🇱", code: "AL", dialCode: "+355" },
  { name: "Algéria", flag: "🇩🇿", code: "DZ", dialCode: "+213" },
  { name: "Samoa Americana", flag: "🇦🇸", code: "AS", dialCode: "+1684" },
  { name: "Andorra", flag: "🇦🇩", code: "AD", dialCode: "+376" },
  { name: "Angola", flag: "🇦🇴", code: "AO", dialCode: "+244" },
  { name: "Anguila", flag: "🇦🇮", code: "AI", dialCode: "+1264" },
  { name: "Antarctida", flag: "��🇶", code: "AQ", dialCode: "+672" },
  { name: "Antigua e Barbuda", flag: "🇦🇬", code: "AG", dialCode: "+1268" },
  { name: "Argentina", flag: "🇦🇷", code: "AR", dialCode: "+54" },
  { name: "Arménia", flag: "🇦🇲", code: "AM", dialCode: "+374" },
  { name: "Aruba", flag: "🇦🇼", code: "AW", dialCode: "+297" },
  { name: "Austrália", flag: "🇦🇺", code: "AU", dialCode: "+61" },
  { name: "Áustria", flag: "🇦🇹", code: "AT", dialCode: "+43" },
  { name: "Azerbaijão", flag: "🇦🇿", code: "AZ", dialCode: "+994" },
  { name: "Bahamas", flag: "🇧🇸", code: "BS", dialCode: "+1242" },
  { name: "Bahrein", flag: "🇧🇭", code: "BH", dialCode: "+973" },
  { name: "Bangladesh", flag: "🇧🇩", code: "BD", dialCode: "+880" },
  { name: "Barbados", flag: "🇧🇧", code: "BB", dialCode: "+1246" },
  { name: "Bielorrússia", flag: "🇧🇾", code: "BY", dialCode: "+375" },
  { name: "Bélgica", flag: "🇧🇪", code: "BE", dialCode: "+32" },
  { name: "Belize", flag: "🇧🇿", code: "BZ", dialCode: "+501" },
  { name: "Benin", flag: "🇧🇯", code: "BJ", dialCode: "+229" },
  { name: "Bermuda", flag: "🇧🇲", code: "BM", dialCode: "+1441" },
  { name: "Butão", flag: "🇧🇹", code: "BT", dialCode: "+975" },
  { name: "Bolívia", flag: "🇧🇴", code: "BO", dialCode: "+591" },
  { name: "Bósnia e Herzegovina", flag: "🇧🇦", code: "BA", dialCode: "+387" },
  { name: "Botswana", flag: "🇧🇼", code: "BW", dialCode: "+267" },
  { name: "Ilha Bouvet", flag: "🇧🇻", code: "BV", dialCode: "+47" },
  { name: "Brasil", flag: "🇧🇷", code: "BR", dialCode: "+55" },
  { name: "Território Britânico do Oceano Índico", flag: "🇮🇴", code: "IO", dialCode: "+246" },
  { name: "Brunei", flag: "🇧🇳", code: "BN", dialCode: "+673" },
  { name: "Bulgária", flag: "🇧🇬", code: "BG", dialCode: "+359" },
  { name: "Burkina Faso", flag: "🇧🇫", code: "BF", dialCode: "+226" },
  { name: "Burundi", flag: "🇧🇮", code: "BI", dialCode: "+257" },
  { name: "Camboja", flag: "🇰🇭", code: "KH", dialCode: "+855" },
  { name: "Camarões", flag: "🇨🇲", code: "CM", dialCode: "+237" },
  { name: "Canadá", flag: "🇨🇦", code: "CA", dialCode: "+1" },
  { name: "Cabo Verde", flag: "🇨🇻", code: "CV", dialCode: "+238" },
  { name: "Ilhas Caimão", flag: "🇰🇾", code: "KY", dialCode: "+345" },
  { name: "República Centro Africana", flag: "🇨🇫", code: "CF", dialCode: "+236" },
  { name: "Chade", flag: "🇹🇩", code: "TD", dialCode: "+235" },
  { name: "Chile", flag: "🇨🇱", code: "CL", dialCode: "+56" },
  { name: "China", flag: "🇨🇳", code: "CN", dialCode: "+86" },
  { name: "Ilha Christmas", flag: "🇨🇽", code: "CX", dialCode: "+61" },
  { name: "Ilhas Cocos (Keeling)", flag: "🇨🇨", code: "CC", dialCode: "+61" },
  { name: "Colômbia", flag: "🇨🇴", code: "CO", dialCode: "+57" },
  { name: "Comores", flag: "🇰🇲", code: "KM", dialCode: "+269" },
  { name: "Congo", flag: "🇨🇬", code: "CG", dialCode: "+242" },
  { name: "Congo, República Democrática do Congo", flag: "🇨🇩", code: "CD", dialCode: "+243" },
  { name: "Ilhas Cook", flag: "🇨🇰", code: "CK", dialCode: "+682" },
  { name: "Costa Rica", flag: "🇨🇷", code: "CR", dialCode: "+506" },
  { name: "Costa do Marfim", flag: "🇨🇮", code: "CI", dialCode: "+225" },
  { name: "Croácia", flag: "🇭🇷", code: "HR", dialCode: "+385" },
  { name: "Cuba", flag: "🇨🇺", code: "CU", dialCode: "+53" },
  { name: "Chipre", flag: "🇨🇾", code: "CY", dialCode: "+357" },
  { name: "República Checa", flag: "🇨🇿", code: "CZ", dialCode: "+420" },
  { name: "Dinamarca", flag: "🇩🇰", code: "DK", dialCode: "+45" },
  { name: "Djibouti", flag: "🇩🇯", code: "DJ", dialCode: "+253" },
  { name: "Dominica", flag: "🇩🇲", code: "DM", dialCode: "+1767" },
  { name: "República Dominicana", flag: "🇩🇴", code: "DO", dialCode: "+1849" },
  { name: "Equador", flag: "🇪🇨", code: "EC", dialCode: "+593" },
  { name: "Egito", flag: "🇪🇬", code: "EG", dialCode: "+20" },
  { name: "El Salvador", flag: "🇸🇻", code: "SV", dialCode: "+503" },
  { name: "Guiné Equatorial", flag: "🇬🇶", code: "GQ", dialCode: "+240" },
  { name: "Eritreia", flag: "🇪🇷", code: "ER", dialCode: "+291" },
  { name: "Estónia", flag: "🇪🇪", code: "EE", dialCode: "+372" },
  { name: "Etiópia", flag: "🇪🇹", code: "ET", dialCode: "+251" },
  { name: "Ilhas Falkland (Malvinas)", flag: "🇫🇰", code: "FK", dialCode: "+500" },
  { name: "Ilhas Faroé", flag: "🇫🇴", code: "FO", dialCode: "+298" },
  { name: "Fiji", flag: "🇫🇯", code: "FJ", dialCode: "+679" },
  { name: "Finlândia", flag: "🇫🇮", code: "FI", dialCode: "+358" },
  { name: "França", flag: "🇫🇷", code: "FR", dialCode: "+33" },
  { name: "Guiana Francesa", flag: "🇬🇫", code: "GF", dialCode: "+594" },
  { name: "Polinésia Francesa", flag: "🇵🇫", code: "PF", dialCode: "+689" },
  { name: "Territórios Franceses do Sul", flag: "🇹🇫", code: "TF", dialCode: "+262" },
  { name: "Gabão", flag: "🇬🇦", code: "GA", dialCode: "+241" },
  { name: "Gâmbia", flag: "🇬🇲", code: "GM", dialCode: "+220" },
  { name: "Geórgia", flag: "🇬🇪", code: "GE", dialCode: "+995" },
  { name: "Alemanha", flag: "🇩🇪", code: "DE", dialCode: "+49" },
  { name: "Gana", flag: "🇬🇭", code: "GH", dialCode: "+233" },
  { name: "Gibraltar", flag: "��🇮", code: "GI", dialCode: "+350" },
  { name: "Grécia", flag: "🇬🇷", code: "GR", dialCode: "+30" },
  { name: "Gronelândia", flag: "🇬🇱", code: "GL", dialCode: "+299" },
  { name: "Granada", flag: "🇬🇩", code: "GD", dialCode: "+1473" },
  { name: "Guadalupe", flag: "🇬🇵", code: "GP", dialCode: "+590" },
  { name: "Guam", flag: "🇬🇺", code: "GU", dialCode: "+1671" },
  { name: "Guatemala", flag: "🇬🇹", code: "GT", dialCode: "+502" },
  { name: "Guernsey", flag: "🇬🇬", code: "GG", dialCode: "+44" },
  { name: "Guiné", flag: "🇬🇳", code: "GN", dialCode: "+224" },
  { name: "Guiné-Bissau", flag: "🇬🇼", code: "GW", dialCode: "+245" },
  { name: "Guiana", flag: "🇬🇾", code: "GY", dialCode: "+592" },
  { name: "Haiti", flag: "🇭🇹", code: "HT", dialCode: "+509" },
  { name: "Ilha Heard e Ilhas McDonald", flag: "🇭🇲", code: "HM", dialCode: "+672" },
  { name: "Santa Sé (Cidade do Vaticano)", flag: "🇻🇦", code: "VA", dialCode: "+379" },
  { name: "Honduras", flag: "🇭🇳", code: "HN", dialCode: "+504" },
  { name: "Hong Kong", flag: "🇭🇰", code: "HK", dialCode: "+852" },
  { name: "Hungria", flag: "🇭🇺", code: "HU", dialCode: "+36" },
  { name: "Islândia", flag: "🇮🇸", code: "IS", dialCode: "+354" },
  { name: "Índia", flag: "🇮🇳", code: "IN", dialCode: "+91" },
  { name: "Indonésia", flag: "🇮🇩", code: "ID", dialCode: "+62" },
  { name: "Irão, República Islâmica do Golfo Pérsico", flag: "🇮🇷", code: "IR", dialCode: "+98" },
  { name: "Iraque", flag: "🇮🇶", code: "IQ", dialCode: "+964" },
  { name: "Irlanda", flag: "🇮🇪", code: "IE", dialCode: "+353" },
  { name: "Ilha de Man", flag: "🇮🇲", code: "IM", dialCode: "+44" },
  { name: "Israel", flag: "🇮🇱", code: "IL", dialCode: "+972" },
  { name: "Itália", flag: "🇮🇹", code: "IT", dialCode: "+39" },
  { name: "Jamaica", flag: "🇯🇲", code: "JM", dialCode: "+1876" },
  { name: "Japão", flag: "🇯🇵", code: "JP", dialCode: "+81" },
  { name: "Jersey", flag: "🇯🇪", code: "JE", dialCode: "+44" },
  { name: "Jordânia", flag: "🇯🇴", code: "JO", dialCode: "+962" },
  { name: "Cazaquistão", flag: "🇰🇿", code: "KZ", dialCode: "+7" },
  { name: "Quénia", flag: "🇰🇪", code: "KE", dialCode: "+254" },
  { name: "Kiribati", flag: "🇰🇮", code: "KI", dialCode: "+686" },
  { name: "Coreia, República Popular Democrática da Coreia", flag: "🇰🇵", code: "KP", dialCode: "+850" },
  { name: "Coreia, República da Coreia do Sul", flag: "🇰🇷", code: "KR", dialCode: "+82" },
  { name: "Kosovo", flag: "🇽🇰", code: "XK", dialCode: "+383" },
  { name: "Kuwait", flag: "🇰🇼", code: "KW", dialCode: "+965" },
  { name: "Quirguistão", flag: "🇰🇬", code: "KG", dialCode: "+996" },
  { name: "Laos", flag: "🇱🇦", code: "LA", dialCode: "+856" },
  { name: "Letónia", flag: "🇱🇻", code: "LV", dialCode: "+371" },
  { name: "Líbano", flag: "🇱🇧", code: "LB", dialCode: "+961" },
  { name: "Lesoto", flag: "🇱🇸", code: "LS", dialCode: "+266" },
  { name: "Libéria", flag: "🇱🇷", code: "LR", dialCode: "+231" },
  { name: "Jamahiriya Árabe da Líbia", flag: "🇱🇾", code: "LY", dialCode: "+218" },
  { name: "Liechtenstein", flag: "🇱🇮", code: "LI", dialCode: "+423" },
  { name: "Lituânia", flag: "🇱🇹", code: "LT", dialCode: "+370" },
  { name: "Luxemburgo", flag: "🇱🇺", code: "LU", dialCode: "+352" },
  { name: "Macau", flag: "🇲🇴", code: "MO", dialCode: "+853" },
  { name: "Macedónia", flag: "🇲🇰", code: "MK", dialCode: "+389" },
  { name: "Madagáscar", flag: "🇲🇬", code: "MG", dialCode: "+261" },
  { name: "Malawi", flag: "🇲🇼", code: "MW", dialCode: "+265" },
  { name: "Malásia", flag: "🇲🇾", code: "MY", dialCode: "+60" },
  { name: "Maldivas", flag: "🇲🇻", code: "MV", dialCode: "+960" },
  { name: "Mali", flag: "🇲🇱", code: "ML", dialCode: "+223" },
  { name: "Malta", flag: "🇲🇹", code: "MT", dialCode: "+356" },
  { name: "Ilhas Marshall", flag: "🇲🇭", code: "MH", dialCode: "+692" },
  { name: "Martinica", flag: "🇲🇶", code: "MQ", dialCode: "+596" },
  { name: "Mauritânia", flag: "🇲🇷", code: "MR", dialCode: "+222" },
  { name: "Maurícia", flag: "🇲🇺", code: "MU", dialCode: "+230" },
  { name: "Mayotte", flag: "🇾🇹", code: "YT", dialCode: "+262" },
  { name: "México", flag: "🇲🇽", code: "MX", dialCode: "+52" },
  { name: "Micronésia, Estados Federados da Micronésia", flag: "🇫🇲", code: "FM", dialCode: "+691" },
  { name: "Moldávia", flag: "🇲🇩", code: "MD", dialCode: "+373" },
  { name: "Mónaco", flag: "🇲🇨", code: "MC", dialCode: "+377" },
  { name: "Mongólia", flag: "🇲🇳", code: "MN", dialCode: "+976" },
  { name: "Montenegro", flag: "🇲🇪", code: "ME", dialCode: "+382" },
  { name: "Montserrat", flag: "🇲🇸", code: "MS", dialCode: "+1664" },
  { name: "Marrocos", flag: "🇲🇦", code: "MA", dialCode: "+212" },
  { name: "Moçambique", flag: "🇲🇿", code: "MZ", dialCode: "+258" },
  { name: "Myanmar", flag: "🇲🇲", code: "MM", dialCode: "+95" },
  { name: "Namíbia", flag: "🇳🇦", code: "NA", dialCode: "+264" },
  { name: "Nauru", flag: "🇳🇷", code: "NR", dialCode: "+674" },
  { name: "Nepal", flag: "🇳🇵", code: "NP", dialCode: "+977" },
  { name: "Países Baixos", flag: "🇳🇱", code: "NL", dialCode: "+31" },
  { name: "Antilhas Holandesas", flag: "", code: "AN", dialCode: "+599" },
  { name: "Nova Caledónia", flag: "🇳🇨", code: "NC", dialCode: "+687" },
  { name: "Nova Zelândia", flag: "��🇿", code: "NZ", dialCode: "+64" },
  { name: "Nicarágua", flag: "🇳🇮", code: "NI", dialCode: "+505" },
  { name: "Níger", flag: "🇳🇪", code: "NE", dialCode: "+227" },
  { name: "Nigéria", flag: "🇳🇬", code: "NG", dialCode: "+234" },
  { name: "Niue", flag: "🇳🇺", code: "NU", dialCode: "+683" },
  { name: "Ilha Norfolk", flag: "🇳🇫", code: "NF", dialCode: "+672" },
  { name: "Ilhas Marianas do Norte", flag: "🇲🇵", code: "MP", dialCode: "+1670" },
  { name: "Noruega", flag: "🇳🇴", code: "NO", dialCode: "+47" },
  { name: "Omã", flag: "🇴🇲", code: "OM", dialCode: "+968" },
  { name: "Paquistão", flag: "🇵🇰", code: "PK", dialCode: "+92" },
  { name: "Palau", flag: "🇵🇼", code: "PW", dialCode: "+680" },
  { name: "Palestina", flag: "🇵🇸", code: "PS", dialCode: "+970" },
  { name: "Panamá", flag: "🇵🇦", code: "PA", dialCode: "+507" },
  { name: "Papua-Nova Guiné", flag: "🇵🇬", code: "PG", dialCode: "+675" },
  { name: "Paraguai", flag: "🇵🇾", code: "PY", dialCode: "+595" },
  { name: "Peru", flag: "🇵🇪", code: "PE", dialCode: "+51" },
  { name: "Filipinas", flag: "🇵🇭", code: "PH", dialCode: "+63" },
  { name: "Pitcairn", flag: "🇵🇳", code: "PN", dialCode: "+64" },
  { name: "Polónia", flag: "🇵🇱", code: "PL", dialCode: "+48" },
  { name: "Porto Rico", flag: "��🇷", code: "PR", dialCode: "+1939" },
  { name: "Catar", flag: "🇶🇦", code: "QA", dialCode: "+974" },
  { name: "Roménia", flag: "🇷🇴", code: "RO", dialCode: "+40" },
  { name: "Rússia", flag: "🇷🇺", code: "RU", dialCode: "+7" },
  { name: "Ruanda", flag: "🇷🇼", code: "RW", dialCode: "+250" },
  { name: "Reunião", flag: "🇷🇪", code: "RE", dialCode: "+262" },
  { name: "São Bartolomeu", flag: "🇧🇱", code: "BL", dialCode: "+590" },
  { name: "Santa Helena, Ascensão e Tristão da Cunha", flag: "🇸🇭", code: "SH", dialCode: "+290" },
  { name: "São Cristóvão e Neves", flag: "🇰🇳", code: "KN", dialCode: "+1869" },
  { name: "Santa Lúcia", flag: "🇱🇨", code: "LC", dialCode: "+1758" },
  { name: "São Martinho", flag: "🇲🇫", code: "MF", dialCode: "+590" },
  { name: "São Pedro e Miquelon", flag: "🇵🇲", code: "PM", dialCode: "+508" },
  { name: "São Vicente e Granadinas", flag: "🇻🇨", code: "VC", dialCode: "+1784" },
  { name: "Samoa", flag: "🇼🇸", code: "WS", dialCode: "+685" },
  { name: "São Marinho", flag: "🇸🇲", code: "SM", dialCode: "+378" },
  { name: "São Tomé e Príncipe", flag: "🇸🇹", code: "ST", dialCode: "+239" },
  { name: "Arábia Saudita", flag: "🇸🇦", code: "SA", dialCode: "+966" },
  { name: "Senegal", flag: "🇸🇳", code: "SN", dialCode: "+221" },
  { name: "Sérvia", flag: "🇷🇸", code: "RS", dialCode: "+381" },
  { name: "Seicheles", flag: "🇸🇨", code: "SC", dialCode: "+248" },
  { name: "Serra Leoa", flag: "🇸🇱", code: "SL", dialCode: "+232" },
  { name: "Singapura", flag: "🇸🇬", code: "SG", dialCode: "+65" },
  { name: "Eslováquia", flag: "🇸🇰", code: "SK", dialCode: "+421" },
  { name: "Eslovénia", flag: "🇸🇮", code: "SI", dialCode: "+386" },
  { name: "Ilhas Salomão", flag: "🇸🇧", code: "SB", dialCode: "+677" },
  { name: "Somália", flag: "🇸🇴", code: "SO", dialCode: "+252" },
  { name: "África do Sul", flag: "🇿🇦", code: "ZA", dialCode: "+27" },
  { name: "Sudão do Sul", flag: "🇸🇸", code: "SS", dialCode: "+211" },
  { name: "Geórgia do Sul e Ilhas Sandwich do Sul", flag: "🇬🇸", code: "GS", dialCode: "+500" },
  { name: "Espanha", flag: "🇪🇸", code: "ES", dialCode: "+34" },
  { name: "Sri Lanka", flag: "🇱🇰", code: "LK", dialCode: "+94" },
  { name: "Sudão", flag: "🇸🇩", code: "SD", dialCode: "+249" },
  { name: "Suriname", flag: "🇸🇷", code: "SR", dialCode: "+597" },
  { name: "Svalbard e Jan Mayen", flag: "🇸🇯", code: "SJ", dialCode: "+47" },
  { name: "Suazilândia", flag: "🇸🇿", code: "SZ", dialCode: "+268" },
  { name: "Suécia", flag: "🇸🇪", code: "SE", dialCode: "+46" },
  { name: "Suíça", flag: "🇨🇭", code: "CH", dialCode: "+41" },
  { name: "República Árabe Síria", flag: "🇸🇾", code: "SY", dialCode: "+963" },
  { name: "Taiwan", flag: "🇹🇼", code: "TW", dialCode: "+886" },
  { name: "Tajiquistão", flag: "🇹🇯", code: "TJ", dialCode: "+992" },
  { name: "Tanzânia, República Unida da Tanzânia", flag: "🇹🇿", code: "TZ", dialCode: "+255" },
  { name: "Tailândia", flag: "🇹🇭", code: "TH", dialCode: "+66" },
  { name: "Timor-Leste", flag: "🇹🇱", code: "TL", dialCode: "+670" },
  { name: "Togo", flag: "🇹🇬", code: "TG", dialCode: "+228" },
  { name: "Tokelau", flag: "🇹🇰", code: "TK", dialCode: "+690" },
  { name: "Tonga", flag: "🇹🇴", code: "TO", dialCode: "+676" },
  { name: "Trindade e Tobago", flag: "🇹🇹", code: "TT", dialCode: "+1868" },
  { name: "Tunísia", flag: "🇹🇳", code: "TN", dialCode: "+216" },
  { name: "Türkiye", flag: "🇹🇷", code: "TR", dialCode: "+90" },
  { name: "Turquemenistão", flag: "🇹🇲", code: "TM", dialCode: "+993" },
  { name: "Ilhas Turcas e Caicos", flag: "��🇨", code: "TC", dialCode: "+1649" },
  { name: "Tuvalu", flag: "🇹🇻", code: "TV", dialCode: "+688" },
  { name: "Uganda", flag: "🇺🇬", code: "UG", dialCode: "+256" },
  { name: "Ucrânia", flag: "🇺🇦", code: "UA", dialCode: "+380" },
  { name: "Emirados Árabes Unidos", flag: "🇦🇪", code: "AE", dialCode: "+971" },
  { name: "Reino Unido", flag: "🇬🇧", code: "GB", dialCode: "+44" },
  { name: "Estados Unidos", flag: "🇺🇸", code: "US", dialCode: "+1" },
  { name: "Uruguai", flag: "🇺🇾", code: "UY", dialCode: "+598" },
  { name: "Usbequistão", flag: "🇺🇿", code: "UZ", dialCode: "+998" },
  { name: "Vanuatu", flag: "🇻🇺", code: "VU", dialCode: "+678" },
  { name: "Venezuela, República Bolivariana da Venezuela", flag: "🇻🇪", code: "VE", dialCode: "+58" },
  { name: "Vietname", flag: "🇻🇳", code: "VN", dialCode: "+84" },
  { name: "Ilhas Virgens Britânicas", flag: "🇻🇬", code: "VG", dialCode: "+1284" },
  { name: "Ilhas Virgens Americanas", flag: "🇻🇮", code: "VI", dialCode: "+1340" },
  { name: "Wallis e Futuna", flag: "��🇫", code: "WF", dialCode: "+681" },
  { name: "Iémen", flag: "🇾🇪", code: "YE", dialCode: "+967" },
  { name: "Zâmbia", flag: "🇿🇲", code: "ZM", dialCode: "+260" },
  { name: "Zimbábue", flag: "🇿🇼", code: "ZW", dialCode: "+263" }
];

export default countries;
